
# "LCD"
set_property PACKAGE_PIN T15 [get_ports {lcd_int_i}]
set_property PACKAGE_PIN U17 [get_ports {lcd_clk_o}]
set_property PACKAGE_PIN W16 [get_ports {lcd_de_o}]
set_property PACKAGE_PIN V16 [get_ports {lcd_hs_o}]
set_property PACKAGE_PIN P15 [get_ports {lcd_vs_o}]
set_property PACKAGE_PIN P16 [get_ports {lcd_pwm_o}]
set_property PACKAGE_PIN W15 [get_ports {lcd_wake_n_o}]
set_property PACKAGE_PIN U19 [get_ports {lcd_bl_en_o}]
set_property PACKAGE_PIN T14 [get_ports {lcd_iic_scl_io}]
set_property PACKAGE_PIN V15 [get_ports {lcd_iic_sda_io}]

set_property PACKAGE_PIN V20 [get_ports {lcd_r_o[0]}]
set_property PACKAGE_PIN T20 [get_ports {lcd_r_o[1]}]
set_property PACKAGE_PIN W20 [get_ports {lcd_r_o[2]}]
set_property PACKAGE_PIN U20 [get_ports {lcd_r_o[3]}]
set_property PACKAGE_PIN Y18 [get_ports {lcd_r_o[4]}]
set_property PACKAGE_PIN N20 [get_ports {lcd_r_o[5]}]
set_property PACKAGE_PIN Y19 [get_ports {lcd_r_o[6]}]
set_property PACKAGE_PIN P20 [get_ports {lcd_r_o[7]}]

set_property PACKAGE_PIN Y16 [get_ports {lcd_g_o[0]}]
set_property PACKAGE_PIN N17 [get_ports {lcd_g_o[1]}]
set_property PACKAGE_PIN Y17 [get_ports {lcd_g_o[2]}]
set_property PACKAGE_PIN P18 [get_ports {lcd_g_o[3]}]
set_property PACKAGE_PIN W18 [get_ports {lcd_g_o[4]}]
set_property PACKAGE_PIN T17 [get_ports {lcd_g_o[5]}]
set_property PACKAGE_PIN V17 [get_ports {lcd_g_o[6]}]
set_property PACKAGE_PIN R16 [get_ports {lcd_g_o[7]}]

set_property PACKAGE_PIN V18 [get_ports {lcd_b_o[0]}]
set_property PACKAGE_PIN R17 [get_ports {lcd_b_o[1]}]
set_property PACKAGE_PIN U14 [get_ports {lcd_b_o[2]}]
set_property PACKAGE_PIN N18 [get_ports {lcd_b_o[3]}]
set_property PACKAGE_PIN U15 [get_ports {lcd_b_o[4]}]
set_property PACKAGE_PIN P19 [get_ports {lcd_b_o[5]}]
set_property PACKAGE_PIN T16 [get_ports {lcd_b_o[6]}]
set_property PACKAGE_PIN U18 [get_ports {lcd_b_o[7]}]


set_property IOSTANDARD LVCMOS33 [get_ports {lcd_int_i}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_clk_o}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_de_o}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_hs_o}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_vs_o}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_pwm_o}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_wake_n_o}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_bl_en_o}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_iic_scl_io}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_iic_sda_io}]

set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b_o[7]}]

# ADC
set_property IOSTANDARD LVCMOS33 [get_ports {dch1_in_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dch1_in_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dch1_in_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dch1_in_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dch1_in_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dch1_in_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dch1_in_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dch1_in_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dch2_in_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dch2_in_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dch2_in_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dch2_in_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dch2_in_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dch2_in_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dch2_in_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dch2_in_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_ch1_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_ch1_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_ch2_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_ch2_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports sclka_0]
set_property IOSTANDARD LVCMOS33 [get_ports sclkb_0]
set_property PACKAGE_PIN G18 [get_ports sclka_0]
set_property PACKAGE_PIN L16 [get_ports sclkb_0]
set_property PACKAGE_PIN E17 [get_ports {switch_ch1_0[1]}]
set_property PACKAGE_PIN G19 [get_ports {switch_ch1_0[0]}]
set_property PACKAGE_PIN G17 [get_ports {switch_ch2_0[1]}]
set_property PACKAGE_PIN F19 [get_ports {switch_ch2_0[0]}]
set_property PACKAGE_PIN L14 [get_ports {dch1_in_0[7]}]
set_property PACKAGE_PIN L15 [get_ports {dch1_in_0[6]}]
set_property PACKAGE_PIN H20 [get_ports {dch1_in_0[5]}]
set_property PACKAGE_PIN J14 [get_ports {dch1_in_0[4]}]
set_property PACKAGE_PIN J20 [get_ports {dch1_in_0[3]}]
set_property PACKAGE_PIN K14 [get_ports {dch1_in_0[2]}]
set_property PACKAGE_PIN H18 [get_ports {dch1_in_0[1]}]
set_property PACKAGE_PIN L17 [get_ports {dch1_in_0[0]}]
set_property PACKAGE_PIN F16 [get_ports {dch2_in_0[7]}]
set_property PACKAGE_PIN E18 [get_ports {dch2_in_0[6]}]
set_property PACKAGE_PIN F17 [get_ports {dch2_in_0[5]}]
set_property PACKAGE_PIN E19 [get_ports {dch2_in_0[4]}]
set_property PACKAGE_PIN C20 [get_ports {dch2_in_0[3]}]
set_property PACKAGE_PIN D19 [get_ports {dch2_in_0[2]}]
set_property PACKAGE_PIN B20 [get_ports {dch2_in_0[1]}]
set_property PACKAGE_PIN D20 [get_ports {dch2_in_0[0]}]


# "BOTTUN 0"
set_property PACKAGE_PIN R19 [get_ports {button_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button_i[0]}]
# "BOTTUN 1"
set_property PACKAGE_PIN T19 [get_ports {button_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button_i[1]}]

# "LED0"
set_property PACKAGE_PIN J16 [get_ports {led_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[0]}]

# "LED1"
set_property PACKAGE_PIN K16 [get_ports {led_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[1]}]
# "LED2"
set_property PACKAGE_PIN G15 [get_ports {led_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[2]}]

# "LED3"
set_property PACKAGE_PIN M20 [get_ports {led_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[3]}]
# "LED4 NOT USED"
set_property PACKAGE_PIN H15 [get_ports {led_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[4]}]


#set_property SEVERITY {Warning} [get_drc_checks NSTD-1]
#set_property SEVERITY {Warning} [get_drc_checks UCIO-1]
######################################################################################



